spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/
  mvc:
    view:
      prefix: /pages/
      suffix: .html
server:
  port: 9200
  servlet:
    context-path: /
